version: '3.7'

services:
  gsc:
    image: gsf/gsc:latest
    restart: always
    container_name: gsc
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    # volumes:
    #   - ./:/home
    # environment:
    #   register_addr: zk1:2181
    # networks:
    #   - gsf-net
  register:
    image: zookeeper
    restart: always
    container_name: zk1
    ports:
      - "2181:2181"
#     networks:
#       - gsf-net

# networks:
#   gsf-net:
#     name: gsf-net