version: '3.7'

services:
  gsc:
    image: gsf/gsc:latest
    restart: always
    container_name: gsc
    ports:
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
    volumes:
      - ./:/etc
    networks:
      - gsf-net
  zk1:
    image: zookeeper
    restart: always
    container_name: zk1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - gsf-net
  zk2:
    image: zookeeper
    restart: always
    container_name: zk2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - gsf-net
  zk3:
    image: zookeeper
    restart: always
    container_name: zk3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - gsf-net

networks:
  gsf-net:
    name: gsf-net